export const ROUTE_PATH = {
  ROOT: "/",
  OWNER: "/portal/owner",
  RENTAL: "/portal",
  ADMIN: "/admin",

  HOME: "home",
  SIGN_IN: "sign-in",
  SIGN_UP: "sign-up",
  TEAM: "team",
  TEAM_DETAIL: "team",
  FAQ: "faq",
  BLOG: "blog/",
  BLOG_DETAIL: "blog",
  CONTACT_US: "contact",
  BROWSE: "browse",
  BROWSE_MAP: "browse/results/map",
  BROWSE_MAP_FULL: "browse/map",
  FORGOT_PASSWORD: "forgot-password",
  RESET_PASSWORD: "reset-password",
  PRIVACY_POLICY: "privacy-policy",
  RENTAL_INQUIRY: 'inquiry',
  RENTAL_SEARCH_RESULT: 'inquiry-search-result',
  RENTAL_MATCHING_PROPERTIES: 'matching-property',
  RENTAL_INQUIRY_EDIT: 'inquiry-edit',

  PROPERTY_DETAIL: "property-detail",
  COPORATE_HOUSING_DC: "coporatehousingwashingtondc",
  FURNISHED_APPARTMENT_DC: "furnishedapartmentsinwashingtondc",
  WASHINGTON_DC_COPORATE_HOUSING: "WashingtonDCcorporatehousing",
  WASHINGTON_DC_TEMPORARY_HOUSING: "WashingtonDCtemporaryhousing",
  SHORT_TERM_RENTAL_DC: "ShortTermFurnishedrentalWashingtonDC",
  SHORT_TERM_HOUSING_DC: "ShortTermHousingWashingtonDC",
  COPORATE_APPARTMENTS_DC: "CorporateApartmentsWashingtonDC",
  FURNISHED_RENTALS: "FurnishedRentalsWashingtonDC",
  MILITARY_HOUSING_DC: "militaryhousingwashingtondc",
   
  //owner
  OWNER_SERVICES: "ownerServices",
  OWNER_INQUIRY: "owner-inquiry",
  OWNER_DASHBOARD: "dashboard",
  OWNER_PROPERTY: "properties/all",
  OWNER_PROPERTY_LEASE: "history/leasing",
  OWNER_BLOCK_PROPERTY: "block-dates",
  OWNER_PROFILE: "owner-profile",
  ADD_PROPERTY: "add-property",
  EDIT_PROPERTY: "edit-property",

  //admin
  ADD_USER: "add-user",
  OWNER_INQUIRY_LIST: "owner-inquiry-list",
  OWNER_PROPERTY_LIST: "property-list",
  OWNER_EDIT_PROPERTY: "owner-edit-property",
  PRICE_CALCULATOR: "price-calculator",
  DYNAMIC_PRICING: "dynamic-pricing",
  EDIT_DYNAMIC_PRINCING: "edit-dynamic-pricing",
  PER_DIEM_LISTING: "per_diem_listing",
  FEATURETTE_LISTING: "featurette_listing",
  ADD_EDIT_FEATURETTE: "add_edit_featurette",
  FEATURE_LISTING: "feature_listing",
  USER_MANAGEMENT: "user-manager",
  ADD_EDIT_USERS: "add-edit-users",
  RENTER_INQUIRY_LIST: "renter-inquiry-list",
  ADD_EDIT_RENTAL_INQUIRY: "edit-rental-inquiry",
  ADD_EDIT_OWNER_INQUIRY: "edit-owner-inquiry",

  CREATE_PROPERTY: "create-property",
  UPDATE_PROPERTY: "edit-property",

  BUILDING_LIST: "buildings-list",
  CREATE_BUILDING: "create-building",
  EDIT_BUILDING: "edit-building",

  NEIGHBORHOOD_LIST: "neighborhood-list",
  EDIT_NEIGHBORHOOD: "edit-neighbourhood",
  CREATE_NEIGHBORHOOD: "create-neighbourhood",

  REGIONS_LIST: "regions",
  EDIT_REGION: "edit-region",
  CREATE_REGION: "create-region",

  BLOCK_DATES_LIST: "block-dates",
  CREATE_EDIT_DATE_BLOCK: "create-edit-block-dates",
  LEASE_MANAGER: "lease-manager",
  OPERATION_MANAGER: "operation-manager",
  ACCOUNTING_MANAGER: "accouting-manager",

  FEATURETTE: "featurette/list",
  CREATE_FEATURETTE: "featurette/new",
  EDIT_FEATURETTE: "featurette",

  ADMIN_BLOG: "blog-listing",
  CREATE_BLOG: "create-blog",
  EDIT_BLOG: "edit-blog",

  ADMIN_PROMOTED_PROPERTY: "promoted-listing",
  CREATE_PROMOTED_PROPERTY: "create-promoted-listing",
  EDIT_PROMOTED_PROPERTY: "edit-promoted-listing",

  LEASING_MANAGER_LIST: "lease/list/all",
  EDIT_LEASING: "create-edit-leases",
  ADD_LEASING: "add-lease",
  CURRENT_LEASESE: "lease/list/current",
  FUTURE_LEASES: "lease/list/future",
  INPREPERATION_LEASES:"lease/list/inpreperation",
  CURRENT_PAST_LEASES: "admin/lease/list",
  CURRENT_FUTURE_LEASES: "lease/list/current-future",
  LEASING_INVOICE: "lease/invoice",
  LEASE_INVOICE_DETAIL: "invoice",

  DOCUMENT_LIST: "template/list/gs_group",
  DOCUMENT_VIEW: "template",
  
  RECURRING_RATE: "operations/recurringcleaning/list",
  EDIT_RECURRING_RATE: "operations/recurringcleaning",

  CLEANING_SCHEDULE: "opeartions/cleaning-schedule",

  PROPERTY_COMPARE: "compare",
  
  RENTAL_LEASE: "leaseproperty",
  RENTAL_LEASE_DETAIL: "guest/reservation",
  RENTAL_INVOICE_DETAIL: "guest/invoice",
  //
  RENTER_DASHBOARD: "guest/matchingproperty",
  PAYMENT_SUCCESS: "guest/paymentinfo",

  OWNER_LEASE_DETAIL: "property",
};

export const ROUTE_NAVIGATION_PATH = {
  // Home
  HOME: ROUTE_PATH.ROOT,
  SIGN_IN: ROUTE_PATH.ROOT + ROUTE_PATH.SIGN_IN,
  FORGOT_PASSWORD: ROUTE_PATH.ROOT + ROUTE_PATH.FORGOT_PASSWORD,
  RESET_PASSWORD: ROUTE_PATH.ROOT + ROUTE_PATH.RESET_PASSWORD,
  PRIVACY_POLICY: ROUTE_PATH.ROOT + ROUTE_PATH.PRIVACY_POLICY,
  TEAM: ROUTE_PATH.ROOT + ROUTE_PATH.TEAM,
  TEAM_DETAIL: ROUTE_PATH.ROOT + ROUTE_PATH.TEAM_DETAIL,
  FAQ: ROUTE_PATH.ROOT + ROUTE_PATH.FAQ,
  COPORATE_HOUSING_DC: ROUTE_PATH.ROOT + ROUTE_PATH.COPORATE_HOUSING_DC,
  FURNISHED_APPARTMENT_DC: ROUTE_PATH.ROOT + ROUTE_PATH.FURNISHED_APPARTMENT_DC,
  WASHINGTON_DC_COPORATE_HOUSING: ROUTE_PATH.ROOT + ROUTE_PATH.WASHINGTON_DC_COPORATE_HOUSING,
  WASHINGTON_DC_TEMPORARY_HOUSING: ROUTE_PATH.ROOT + ROUTE_PATH.WASHINGTON_DC_TEMPORARY_HOUSING,
  SHORT_TERM_RENTAL_DC: ROUTE_PATH.ROOT + ROUTE_PATH.SHORT_TERM_RENTAL_DC,
  SHORT_TERM_HOUSING_DC: ROUTE_PATH.ROOT + ROUTE_PATH.SHORT_TERM_HOUSING_DC,
  COPORATE_APPARTMENTS_DC: ROUTE_PATH.ROOT + ROUTE_PATH.COPORATE_APPARTMENTS_DC,
  FURNISHED_RENTALS: ROUTE_PATH.ROOT + ROUTE_PATH.FURNISHED_RENTALS,
  MILITARY_HOUSING_DC: ROUTE_PATH.ROOT + ROUTE_PATH.MILITARY_HOUSING_DC,
  BLOG: ROUTE_PATH.ROOT + ROUTE_PATH.BLOG,
  BLOG_DETAIL: ROUTE_PATH.ROOT + ROUTE_PATH.BLOG_DETAIL,
  CONTACT_US: ROUTE_PATH.ROOT + ROUTE_PATH.CONTACT_US,
  BROWSE: ROUTE_PATH.ROOT + ROUTE_PATH.BROWSE,
  PROPERTY_DETAIL: ROUTE_PATH.ROOT + ROUTE_PATH.PROPERTY_DETAIL,
  BROWSE_MAP: ROUTE_PATH.ROOT + ROUTE_PATH.BROWSE_MAP,
  BROWSE_MAP_FULL: ROUTE_PATH.ROOT + ROUTE_PATH.BROWSE_MAP_FULL,
  // Renter
  RENTAL_INQUIRY: ROUTE_PATH.ROOT + ROUTE_PATH.RENTAL_INQUIRY,
  PROPERTY_COMPARE: ROUTE_PATH.ROOT + ROUTE_PATH.PROPERTY_COMPARE,
  MATCHING_PROPERTY: ROUTE_PATH.ROOT + ROUTE_PATH.RENTAL_MATCHING_PROPERTIES,
  RENTER_DASHBOARD:  ROUTE_PATH.RENTAL + ROUTE_PATH.ROOT + ROUTE_PATH.RENTER_DASHBOARD,
  RENTAL_INQUIRY_EDIT:  ROUTE_PATH.RENTAL + ROUTE_PATH.ROOT + ROUTE_PATH.RENTAL_INQUIRY_EDIT,
  RENTAL_INQUIRY_NEW: ROUTE_PATH.RENTAL + ROUTE_PATH.ROOT + ROUTE_PATH.RENTAL_INQUIRY,
  
  

  //Owner
  OWNER_SERVICES: ROUTE_PATH.ROOT + ROUTE_PATH.OWNER_SERVICES,
  OWNER_INQUIRY: ROUTE_PATH.ROOT + ROUTE_PATH.OWNER_INQUIRY,
  ADD_PROPERTY: ROUTE_PATH.OWNER + ROUTE_PATH.ROOT + ROUTE_PATH.ADD_PROPERTY,
  EDIT_PROPERTY: ROUTE_PATH.OWNER + ROUTE_PATH.ROOT + ROUTE_PATH.EDIT_PROPERTY,
  OWNER_DASHBOARD: ROUTE_PATH.OWNER + ROUTE_PATH.ROOT + ROUTE_PATH.OWNER_DASHBOARD,
  OWNER_PROPERTY: ROUTE_PATH.OWNER + ROUTE_PATH.ROOT + ROUTE_PATH.OWNER_PROPERTY,
  OWNER_PROPERTY_LEASE: ROUTE_PATH.OWNER + ROUTE_PATH.ROOT + ROUTE_PATH.OWNER_PROPERTY_LEASE,
  OWNER_BLOCK_PROPERTY: ROUTE_PATH.OWNER + ROUTE_PATH.ROOT + ROUTE_PATH.OWNER_BLOCK_PROPERTY,
  OWNER_PROFILE: ROUTE_PATH.OWNER + ROUTE_PATH.ROOT + ROUTE_PATH.OWNER_PROFILE,
  OWNER_LEASE_DETAIL: ROUTE_PATH.OWNER + ROUTE_PATH.ROOT + ROUTE_PATH.OWNER_LEASE_DETAIL,

  //Admin
  ADMIN_OWNER_INQUIRY_LIST: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.OWNER_INQUIRY_LIST,
  ADMIN_OWNER_PROPERTY_LIST: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.OWNER_PROPERTY_LIST,
  ADMIN_OWNER_EDIT_PROPERTY: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.OWNER_EDIT_PROPERTY,
  PRICE_CALCULATOR: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.PRICE_CALCULATOR,
  DYNAMIC_PRICING: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.DYNAMIC_PRICING,
  PER_DIEM_LISTING: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.PER_DIEM_LISTING,
  EDIT_DYNAMIC_PRINCING: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.EDIT_DYNAMIC_PRINCING,
  FEATURETTE_LISTING: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.FEATURETTE_LISTING,
  ADD_EDIT_FEATURETTE: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.ADD_EDIT_FEATURETTE,
  FEATURE_LISTING: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.FEATURE_LISTING,
  USER_MANAGEMENT: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.USER_MANAGEMENT,
  ADD_EDIT_USERS: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.ADD_EDIT_USERS,
  ADD_USER: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.ADD_USER,

  ADMIN_RENTER_INQUIRY_LIST: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.RENTER_INQUIRY_LIST,
  ADD_EDIT_RENTAL_INQUIRY: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.ADD_EDIT_RENTAL_INQUIRY,
  
  ADD_EDIT_OWNER_INQUIRY: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.ADD_EDIT_OWNER_INQUIRY,
  
  CREATE_PROPERTY: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.CREATE_PROPERTY,
  UPDATE_PROPERTY: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.UPDATE_PROPERTY,

  CREATE_BUILDING: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.CREATE_BUILDING,
  EDIT_BUILDING: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.EDIT_BUILDING,

  BUILDING_LIST: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.BUILDING_LIST,

  NEIGHBORHOOD_LIST: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.NEIGHBORHOOD_LIST,
  EDIT_NEIGHBORHOOD: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.EDIT_NEIGHBORHOOD,
  CREATE_NEIGHBORHOOD:  ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.CREATE_NEIGHBORHOOD,

  REGIONS_LIST: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.REGIONS_LIST,
  EDIT_REGION: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.EDIT_REGION,
  CREATE_REGION:  ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.CREATE_REGION,

 
  BLOCK_DATES_LIST: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.BLOCK_DATES_LIST,
  CREATE_EDIT_DATE_BLOCK: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.CREATE_EDIT_DATE_BLOCK,
  LEASE_MANAGER: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.LEASE_MANAGER,
  OPERATION_MANAGER: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.OPERATION_MANAGER,

  ACCOUNTING_MANAGER: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.ACCOUNTING_MANAGER,

  FEATURETTE: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.FEATURETTE,
  CREATE_FEATURETTE: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.CREATE_FEATURETTE,
  EDIT_FEATURETTE: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.EDIT_FEATURETTE,

  ADMIN_BLOG: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.ADMIN_BLOG,
  CREATE_BLOG: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.CREATE_BLOG,
  EDIT_BLOG: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.EDIT_BLOG,

  ADMIN_PROMOTED_PROPERTY: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.ADMIN_PROMOTED_PROPERTY,
  CREATE_PROMOTED_PROPERTY: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.CREATE_PROMOTED_PROPERTY,
  EDIT_PROMOTED_PROPERTY: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.EDIT_PROMOTED_PROPERTY,

  LEASING_MANAGER_LIST:ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.LEASING_MANAGER_LIST,
  EDIT_LEASING:ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.EDIT_LEASING,
  ADD_LEASING:ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.ADD_LEASING,
  CURRENT_LEASESE:ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.CURRENT_LEASESE,
  FUTURE_LEASES: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.FUTURE_LEASES,
  INPREPERATION_LEASES: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.INPREPERATION_LEASES,
  CURRENT_PAST_LEASES: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.CURRENT_PAST_LEASES,
  CURRENT_FUTURE_LEASES: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.CURRENT_FUTURE_LEASES,
  LEASING_INVOICE: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.LEASING_INVOICE,
  LEASE_INVOICE_DETAIL: ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.LEASE_INVOICE_DETAIL,

  DOCUMENT_LIST:ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.DOCUMENT_LIST,
  DOCUMENT_VIEW:ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.DOCUMENT_VIEW,
  RECURRING_RATE:ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.RECURRING_RATE,
  EDIT_RECURRING_RATE:ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.EDIT_RECURRING_RATE,
  CLEANING_SCHEDULE:ROUTE_PATH.ADMIN + ROUTE_PATH.ROOT + ROUTE_PATH.CLEANING_SCHEDULE,

  RENTAL_LEASE: ROUTE_PATH.RENTAL + ROUTE_PATH.ROOT + ROUTE_PATH.RENTAL_LEASE,
  RENTAL_LEASE_DETAIL: ROUTE_PATH.RENTAL + ROUTE_PATH.ROOT + ROUTE_PATH.RENTAL_LEASE_DETAIL,
  RENTAL_INVOICE_DETAIL: ROUTE_PATH.RENTAL + ROUTE_PATH.ROOT + ROUTE_PATH.RENTAL_INVOICE_DETAIL,
  PAYMENT_SUCCESS: ROUTE_PATH.RENTAL + ROUTE_PATH.ROOT + ROUTE_PATH.PAYMENT_SUCCESS
};
